version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: currency_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: currency_tracker
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
    networks:
      - currency_tracker_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U currency_user -d currency_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: currency_tracker_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - currency_tracker_network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local

networks:
  currency_tracker_network:
    driver: bridge 